"""create ingestion schema

Revision ID: 2164e9581498
Revises: 
Create Date: 2026-09-18 04:00:38.235338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2164e9581498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_document_id'), 'source_documents', ['document_id'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_document_id'), 'ingestion_runs', ['document_id'], unique=False)
    op.create_table('source_elements',
    sa.Column('element_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('asset_path', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index(op.f('ix_source_elements_document_id'), 'source_elements', ['document_id'], unique=False)
    op.create_table('element_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_element_id', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('target_element_id', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_element_id'], ['source_elements.element_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_element_id'], ['source_elements.element_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_element_id', 'relationship_type', 'target_element_id', name='uq_element_relationship')
    )
    op.create_index(op.f('ix_element_relationships_source_element_id'), 'element_relationships', ['source_element_id'], unique=False)
    op.create_index(op.f('ix_element_relationships_target_element_id'), 'element_relationships', ['target_element_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_relationships_target_element_id'), table_name='element_relationships')
    op.drop_index(op.f('ix_element_relationships_source_element_id'), table_name='element_relationships')
    op.drop_table('element_relationships')
    op.drop_index(op.f('ix_source_elements_document_id'), table_name='source_elements')
    op.drop_table('source_elements')
    op.drop_index(op.f('ix_ingestion_runs_document_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_source_documents_document_id'), table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
